version: "3.9"
services:
  code_server:
    build:
      context: .
      dockerfile: Dockerfile.full
    container_name: "VSCode_Server"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/home/jungle/.opencode-server
