version: "3.9"
services:
  code_server:
    build:
      context: .
      dockerfile: Dockerfile.full
    container_name: "VSCode_Server"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:${VSCODE_SERVER_PORT:-3000}:3000"
    volumes:
      - ./data:/home/jungle/.opencode-server
