name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set VS Code Version Environment Variable
        run: |
          DOCKERFILE_VSCODE_VERSION=$(cat Dockerfile | grep "ARG VSCODE_VERSION" | cut -d "=" -f 2)
          echo "DOCKERHUB_RELEASE=${DOCKERFILE_VSCODE_VERSION}" >> $GITHUB_ENV

      - name: Print DockerHub Release Version
        run: |
          echo "${DOCKERHUB_RELEASE}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: crazyuploader
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push 'vscode_server:latest' Docker Image tag
        run: |
          docker build --file Dockerfile --tag crazyuploader/vscode_server:latest .
          docker push crazyuploader/vscode_server:latest

      - name: Build & Push 'vscode_server:full' Docker Image tag
        run: |
          docker build --file Dockerfile.full --tag crazyuploader/vscode_server:full .
          docker push crazyuploader/vscode_server:full

      - name: List Docker Image(s)
        run: |
          docker images
