name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push vscode_server:latest Docker Image tag
        run: |
          docker build --file Dockerfile --tag crazyuploader/vscode_server:latest .
          docker push crazyuploader/vscode_server:latest

      - name: Build & Push vscode_server:full Docker Image tag
        run: |
          docker build --file Dockerfile --tag crazyuploader/vscode_server:full .
          docker push crazyuploader/vscode_server:full

      - name: List Docker Image(s)
        run: |
          docker images
